WCD/DemoEcommerceModel2/src/com/wpsj/model/ProductFinderBean.java
package com.wpsj.model;

import com.wpsj.da.ProductDataAccess;
import com.wpsj.entity.Product;

import java.util.List;

public class ProductFinderBean {
    private String keyword;
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }
    public List<Product> getProducts(){
        return new
                ProductDataAccess().getProductByName(keyword);
    }
}

WCD/DemoEcommerceModel2/web/index.jsp
<%--
  Created by IntelliJ IDEA.
  User: admin
  Date: 8/28/2020
  Time: 7:59 PM
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
  <head>
    <title>$Title$</title>
  </head>
  <body>
  $END$
  </body>
</html>

WCD/DemoEcommerceModel2/web/result.jsp
<%--
  Created by IntelliJ IDEA.
  User: admin
  Date: 8/28/2020
  Time: 8:04 PM
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>List Product</title>
</head>
<body>
<h1>List Product!</h1>
<a href="search.jsp">Search</a>
<jsp:useBean id="finder" class="com.wpsj.model.ProductFinderBean" scope="request"/>

<table>
    <tr>
        <td>Id</td>
        <td>Name</td>
        <td>Description</td>
    </tr>
    <c:forEach items="${finder.products}" var="product">
        <tr>
            <td><c:out value="${product.id}"/></td>
            <td><c:out value="${product.name}"/></td>
            <td><c:out value="${product.desc}"/></td>
        </tr>
    </c:forEach>
</table>
</body>
</html>

WCD/DemoEcommerceModel2/web/search.jsp
<%--
  Created by IntelliJ IDEA.
  User: admin
  Date: 8/28/2020
  Time: 8:04 PM
  To change this template use File | Settings | File Templates.
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@page contentType="text/html" pageEncoding="UTF-8" %>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Shopping</title>
</head>
<body>
<h1>Product List</h1>
<form action="ProductFinder">
    <span style="color: red;">
        <c:out value="${param.msg}"/>
    </span>
    <input name="name"/>
    <input type="submit"/>
</form>
</body>
</html>